TRUNCATE TABLE public.candidates RESTART IDENTITY;

INSERT INTO public.candidates (name, position, skills, company, category)
VALUES
  ('김민준', 'Backend Developer', ARRAY['Python/Django','Java/Spring Boot','Go/Kubernetes','Node.js'], '카카오', 'Developer'),
  ('이서연', 'Frontend Developer', ARRAY['React','Vue.js','TypeScript','Next.js'], 'Hoya Company', 'Developer'),
  ('박지호', 'Mobile Developer', ARRAY['Swift/iOS','Kotlin/Android','Flutter','Docker'], 'Hoya Company', 'Developer'),
  ('최유진', 'Machine Learning Engineer', ARRAY['Machine Learning','Blockchain','Game Development'], 'Hoya Company', 'Developer'),
  ('정다은', 'UI/UX Designer', ARRAY['Figma','Sketch','Adobe XD','Prototyping'], 'Hoya Company', 'Designer'),
  ('한지민', 'Visual Designer', ARRAY['Branding','Illustration','Motion Graphics'], 'Hoya Company', 'Designer'),
  ('오현우', 'Design System Designer', ARRAY['Design System','Component Library','Tokens'], 'Hoya Company', 'Designer'),
  ('강수빈', 'Product Manager', ARRAY['3D Design','Game UI','Data Visualization'], 'Hoya Company', 'PM'),
  ('조하늘', 'Product Manager', ARRAY['Agile','Scrum','OKR','Lean Startup'], 'Hoya Company', 'PM'),
  ('윤지훈', 'Product Analyst', ARRAY['SQL','Data Analysis','A/B Testing'], 'Hoya Company', 'PM'),
  ('신예린', 'Domain PM', ARRAY['E-commerce','Fintech','Healthcare','Gaming'], 'Hoya Company', 'PM'),
  ('장민재', 'Performance Marketer', ARRAY['SEO','Google Analytics','Performance Marketing'], 'Hoya Company', 'Marketer'),
  ('권서진', 'Content Marketer', ARRAY['Copywriting','Content Strategy','Brand Storytelling'], 'Hoya Company', 'Marketer'),
  ('임하준', 'Growth Marketer', ARRAY['Growth Hacking','Viral Marketing','Community Management'], 'Hoya Company', 'Marketer'),
  ('송지아', 'Community Marketer', ARRAY['Social Media','Influencer','Email Marketing'], 'Hoya Company', 'Marketer'),
  ('홍도윤', 'Backend Developer', ARRAY['Python/Django','Java/Spring Boot','Go/Kubernetes','Node.js'], 'Hoya Company', 'Developer'),
  ('배수아', 'Backend Developer', ARRAY['Java/Spring Boot','Go/Kubernetes','Node.js','TypeScript','Go'], '네이버', 'Developer'),
  ('문채원', 'Backend Developer', ARRAY['Python/Django','Node.js','Go/Kubernetes'], 'Hoya Company', 'Developer'),
  ('백승우', 'Frontend Developer', ARRAY['React','Vue.js','TypeScript','Next.js'], 'Hoya Company', 'Developer'),
  ('서지후', 'Frontend Developer', ARRAY['React','TypeScript','Next.js'], 'Hoya Company', 'Developer'),
  ('남예은', 'Fullstack Developer', ARRAY['Vue.js','TypeScript','React','Node.js','Python/Django','Java/Spring Boot'], 'Hoya Company', 'Developer'),
  ('고태훈', 'Mobile Developer', ARRAY['Swift/iOS','Kotlin/Android','Flutter'], 'Hoya Company', 'Developer'),
  ('류예진', 'Mobile Developer', ARRAY['Swift/iOS','Flutter'], 'Hoya Company', 'Developer'),
  ('안지호', 'Mobile Developer', ARRAY['Kotlin/Android','Flutter'], 'Hoya Company', 'Developer'),
  ('노서윤', 'Machine Learning Engineer', ARRAY['Machine Learning','Python/Django','Go/Kubernetes'], '네이버', 'Developer'),
  ('도현수', 'Blockchain Developer', ARRAY['Blockchain','Node.js','Go/Kubernetes'], 'Hoya Company', 'Developer'),
  ('차민지', 'Game Developer', ARRAY['Game Development','Node.js','Go/Kubernetes'], 'Hoya Company', 'Developer'),
  ('황지수', 'UI/UX Designer', ARRAY['Figma','Sketch','Adobe XD','Prototyping'], 'Hoya Company', 'Designer'),
  ('성준호', 'UI/UX Designer', ARRAY['Figma','Prototyping','Adobe XD'], 'Hoya Company', 'Designer'),
  ('구다빈', 'Visual Designer', ARRAY['Branding','Illustration','Motion Graphics'], 'Hoya Company', 'Designer'),
  ('전우진', 'Visual Designer', ARRAY['Illustration','Motion Graphics','Branding'], 'Hoya Company', 'Designer'),
  ('양다현', 'Design System Designer', ARRAY['Design System','Component Library','Tokens'], 'Hoya Company', 'Designer'),
  ('원시우', 'Design System Designer', ARRAY['Design System','Tokens'], 'Hoya Company', 'Designer'),
  ('하유나', '3D Designer', ARRAY['3D Design','Game UI','Data Visualization'], 'Hoya Company', 'Designer'),
  ('민지원', '3D Designer', ARRAY['3D Design','Data Visualization'], 'Hoya Company', 'Designer'),
  ('진서현', 'Product Manager', ARRAY['Agile','Scrum','OKR','Lean Startup'], 'Hoya Company', 'PM'),
  ('손가은', 'Product Manager', ARRAY['Agile','OKR','Lean Startup'], 'Hoya Company', 'PM'),
  ('유태민', 'Product Analyst', ARRAY['SQL','Data Analysis','A/B Testing'], 'Hoya Company', 'PM'),
  ('서하람', 'Product Analyst', ARRAY['Data Analysis','A/B Testing','SQL'], 'Hoya Company', 'PM'),
  ('고은채', 'Domain PM', ARRAY['E-commerce','Fintech','Healthcare','Gaming'], 'Hoya Company', 'PM'),
  ('주태양', 'Domain PM', ARRAY['Fintech','E-commerce','Gaming'], 'Hoya Company', 'PM'),
  ('나윤아', 'Performance Marketer', ARRAY['SEO','Google Analytics','Performance Marketing'], 'Hoya Company', 'Marketer'),
  ('탁지후', 'Performance Marketer', ARRAY['Performance Marketing','Google Analytics'], 'Hoya Company', 'Marketer'),
  ('길소연', 'Content Marketer', ARRAY['Copywriting','Content Strategy','Brand Storytelling'], 'Hoya Company', 'Marketer'),
  ('심준혁', 'Content Marketer', ARRAY['Content Strategy','Brand Storytelling','Copywriting'], 'Hoya Company', 'Marketer'),
  ('백지민', 'Growth Marketer', ARRAY['Growth Hacking','Viral Marketing','Community Management'], 'Hoya Company', 'Marketer'),
  ('엄유림', 'Growth Marketer', ARRAY['Viral Marketing','Community Management'], 'Hoya Company', 'Marketer'),
  ('곽재훈', 'Community Marketer', ARRAY['Social Media','Influencer','Email Marketing'], 'Hoya Company', 'Marketer'),
  ('변서아', 'Community Marketer', ARRAY['Email Marketing','Social Media','Influencer'], 'Hoya Company', 'Marketer'),
  ('오세진', 'Growth Marketer', ARRAY['Growth Hacking','Community Management','Viral Marketing'], 'Hoya Company', 'Marketer');
