# https://docs.streamlit.io/
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
[theme]

base = "light"

# 대화형 요서에 새앙되는 기본 강조 색상
primaryColor = '#027373'

# 메인 컨텐치 영역
backgroundColor = "#F2EDC"

# 사이드바와 대부분의 대화형 위젯에 사용되는 배경
scondaryBackgroundColor = '#A9D9D0'

# 대부분의 텍스트에 사용되는 생상
textColor = "#0D0D0D"

# 코드 블록을 제외한 앱의 모든 텍스트에 사용되는 글꼴 패밀리
# 'sans serif', 'serif', 'monospace' 중 골라서 사용 가능
font = "monospace"