# https://docs.streamlit.io/
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]
# 기본 테마를 다크로 고정
base = "dark"

# 포인트 컬러(그대로 사용)
primaryColor = "#027373"

# 메인 컨텐츠 배경 (어두운 톤)
backgroundColor = "#0D0D0D"

# 사이드바/위젯 배경 (어두운 보조 톤)
secondaryBackgroundColor = "#1E2A2F"

# 본문 텍스트 색
textColor = "#F2E7DC"

# 폰트 패밀리: 'sans serif' | 'serif' | 'monospace'
font = "monospace"
