# Streamlit Secrets 파일
# 실제 배포 시에는 Streamlit Cloud의 Secrets 기능을 사용하세요

# OpenAI API Key
# openai_api_key = "your-openai-api-key-here"

# Anthropic API Key  
# anthropic_api_key = "your-anthropic-api-key-here"

# LangSmith API Key
# langsmith_api_key = "your-langsmith-api-key-here"
# langsmith_project = "Agentic RAG System"

# 기타 API 키들
# cohere_api_key = "your-cohere-api-key-here"
# google_api_key = "your-google-api-key-here"
# tavily_api_key = "your-tavily-api-key-here"
